'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("List_MP3s.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BETA 0.2.00 &lt;Released DATE&gt;        '''
        ''' - Added tag editing to individual MP3s        '''
        ''' - Added Table Preview        '''
        '''        '''
        '''BETA 0.1.00 (original) &lt;Released 13-Jun-08&gt;        '''
        ''' - List all MP3&apos;s from selected folder        '''
        ''' - Shows ID3v1 tags on selected MP3        '''
        ''' - Generate HTML list of all MP3s in a folder        '''
        '''.
        '''</summary>
        Friend ReadOnly Property changelog() As String
            Get
                Return ResourceManager.GetString("changelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INTRODUCTION        '''
        '''        '''
        '''List MP3&apos;s is a quick program to go through your music library without all the fancy you-ha of        '''
        '''bigger programs (i.e. Windows Media Player, Winamp, Real Player, MusicMatch Jukebox, etc). I        '''
        '''built this program to load quickly, work quickly, then leave, and that&apos;s EXACTLY what this is.        '''
        '''After selecting a folder full of MP3&apos;s, it will load the list of *.mp3 files into the list box        '''
        '''on the right of the window. This is the main starting point.        '''
        '''        '''
        '''Click on an MP3 on the list to view its ID [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PauseHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PauseHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PlayHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @charset &quot;utf-8&quot;;
        '''/* CSS Document */
        '''
        '''th {
        '''	font-family: &quot;Script MT Bold&quot;;
        '''	font-size: 20px;
        '''	font-weight: bolder;
        '''	font-variant: small-caps;
        '''	color: #000000;
        '''	background-color: #CCCCCC;
        '''	text-decoration: underline;
        '''	text-align: center;
        '''	vertical-align: text-top;
        '''	margin: 0px;
        '''	padding: 1px;
        '''}
        '''body {
        '''	font-family: Verdana, Arial, Helvetica, sans-serif;
        '''	font-size: 14px;
        '''	font-style: italic;
        '''	font-weight: normal;
        '''	font-variant: normal;
        '''	color: #CCCCCC;
        '''	background-color: #000000;
        '''}
        '''t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sCSSStylesheet() As String
            Get
                Return ResourceManager.GetString("sCSSStylesheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StopHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;1.0&quot;
        '''xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        '''&lt;xsl:template match=&quot;/&quot;&gt;
        '''  &lt;html&gt;
        '''  &lt;body&gt;
        '''    &lt;h2&gt;My MP3 List&lt;/h2&gt;
        '''    &lt;table border=&quot;1&quot;&gt;
        '''    &lt;tr bgcolor=&quot;#CCCCCC&quot;&gt;
        '''      &lt;th&gt;Artist&lt;/th&gt;
        '''	  &lt;th&gt;Album&lt;/th&gt;
        '''      &lt;th&gt;Title&lt;/th&gt;
        '''	  &lt;th&gt;Genre&lt;/th&gt;
        '''	  &lt;th&gt;Year&lt;/th&gt;
        '''	  &lt;th&gt;Track&lt;/th&gt;
        '''	  &lt;th&gt;Comment&lt;/th&gt;
        '''    &lt;/tr&gt;
        '''    &lt;xsl:for-each select=&quot;ListMP3Library/songdata&quot;&gt;
        '''	&lt;xsl:sort select=&quot;artist&quot;/&gt;
        '''    &lt;tr&gt;
        '''      &lt;td&gt;&lt;b&gt;&lt;xs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sXMLStylesheet() As String
            Get
                Return ResourceManager.GetString("sXMLStylesheet", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
